name       : libtool
version    : 2.4.6
release    : 8
source     :
    - https://ftp.gnu.org/gnu/libtool/libtool-2.4.6.tar.xz : 7c87a8c2c8c0fc9cd5019e402bed4292462d00a718a7cd5f11218153bf28b26f
homepage   : http://www.gnu.org/software/libtool
license    :
    - GPL-2.0
summary    : Generic library support script
component  : programming.library
patterns   :
    - devel : [/usr/bin, /usr/share/aclocal, /usr/share/libtool]
devel      : true
emul32     : yes
description: |
    The Libtool package contains the GNU generic library support script. It wraps the complexity of using shared libraries in a consistent, portable interface.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
