name        : libtool
version     : 2.4.2
release     : 6
source      :
    - http://ftp.gnu.org/gnu/libtool/libtool-2.4.2.tar.xz : 1d7b6862c1ed162e327f083a6f78f40eae29218f0db8c38393d61dab764c4407
homepage    : http://www.gnu.org/software/libtool
license     :
    - GPL-2.0
summary     : Generic library support script
patterns    :
    - devel: [/usr/bin, /usr/share/aclocal, /usr/share/libtool]
devel       : true
description : |
    The Libtool package contains the GNU generic library support script. It wraps the complexity of using shared libraries in a consistent, portable interface.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
