name       : libtool
version    : 2.4.7
release    : 10
source     :
    - https://ftp.gnu.org/gnu/libtool/libtool-2.4.7.tar.xz : 4f7f217f057ce655ff22559ad221a0fd8ef84ad1fc5fcb6990cecc333aa1635d
homepage   : http://www.gnu.org/software/libtool
license    :
    - GPL-2.0-or-later
component  : programming.library
summary    : Generic library support script
description: |
    The Libtool package contains the GNU generic library support script. It wraps the complexity of using shared libraries in a consistent, portable interface.
patterns   :
    - devel : [/usr/bin, /usr/share/aclocal, /usr/share/libtool]
devel      : true
emul32     : yes
builddeps  :
    - libgfortran-32bit # check
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check || :
